; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Aventa HFT Pro 2026 v7.3.3"
#define MyAppVersion "7.3.3"
#define MyAppPublisher "PT Aventa Intelligent Power"
#define MyAppURL "https://www.pt-aip.com/"
#define MyAppExeName "Aventa_HFT_Pro_2026_v7_3_3.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9F7F9238-C6D3-41F5-9394-4C8DB9E10696}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\LICENSE.txt
InfoBeforeFile=D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\INFO_BEFORE.txt
InfoAfterFile=D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\INFO_AFTER.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=Aventa_HFT_Pro_2026_v7_3_3_setup
SetupIconFile=D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\aventa.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\aventa.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\LICENSE_en.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\requirements_optimized.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Aventa AI\Project Aventa\Aventa_HFT_Pro_2026_v733\MLTraining\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

